spring:
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
  datasource:
    url: jdbc:mysql://localhost:3306/mmall?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: nono
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-enums-package: top.wl9939.mmall002.enums
server:
  port: 80
